version: '3'
services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DB_URI=mongodb://mongo:27017/furr-fluff-spa-dev
  mongo:
    image: mongo
    ports:
      - "27017:27017"
